---
abstract: 'PayPoint online payment'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-PayPoint
requires:
  SOAP::Lite: 0
  XML::Writer: 0
resources:
  repository: git://github.com/fayland/p5-Business-PayPoint.git
version: 0.01
